# Generated by Django 5.1.2 on 2024-10-31 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels_front', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=30)),
                ('levels_back', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=30)),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.backend')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.frontend')),
            ],
        ),
    ]
