# Generated by Django 5.1.2 on 2024-10-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='levels_back',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='frontend',
            name='levels_front',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Experienced', 'Experienced')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
