# Generated by Django 5.1.2 on 2024-10-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_backend_levels_back_frontend_levels_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backend',
            old_name='levels_back',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='frontend',
            old_name='levels_front',
            new_name='level',
        ),
    ]
