# Generated by Django 5.1.2 on 2024-10-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_levels_back_backend_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('git_repo', models.CharField(max_length=200, null=True)),
                ('live_demo', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
