# Generated by Django 5.1.2 on 2024-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_demo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
