# Generated by Django 5.1.2 on 2024-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_live_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
